// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXnwMEjEfespysEU645Z3iDyPgInPC5Io',
    appId: '1:266782625015:web:6183ed2d15370c872b17f2',
    messagingSenderId: '266782625015',
    projectId: 'chat-app-135b5',
    authDomain: 'chat-app-135b5.firebaseapp.com',
    storageBucket: 'chat-app-135b5.appspot.com',
    measurementId: 'G-V41KGN657F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4mzQGquQp_1_0vUaYPBaSMZjBGK4DBiQ',
    appId: '1:266782625015:android:ab4d151a68c17b822b17f2',
    messagingSenderId: '266782625015',
    projectId: 'chat-app-135b5',
    storageBucket: 'chat-app-135b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNXgSTukcd6LziELeDXbPsYDqdjrTKFxQ',
    appId: '1:266782625015:ios:0c5f8f3e74320aff2b17f2',
    messagingSenderId: '266782625015',
    projectId: 'chat-app-135b5',
    storageBucket: 'chat-app-135b5.appspot.com',
    iosBundleId: 'com.example.scholarChat',
  );
}
